### ISSUE TITLE
Offset copy area in copy chat

### ISSUE THREAD

**Issue by Wetxius** [funkydude/BasicChatMods#5] opened 2017-09-17 15:16 UTC
v7.3.0 version.
First line selecting is perfect.  But the larger the line, the greater offset for copy. 
![wowscrnshot_091717_180954](https://user-images.githubusercontent.com/1249672/30522138-0ad5b804-9bd4-11e7-8bed-0d996e8dcb98.jpg)
![wowscrnshot_091717_180948](https://user-images.githubusercontent.com/1249672/30522139-0adab606-9bd4-11e7-99d5-deb83798038a.jpg)

**Comment by funkydude** [comment] 2019-10-14 18:19
Duplicate of https://github.com/funkydude/BasicChatMods/issues/14
Waiting for Blizz fix.

**Closed by funkydude** 2019-10-14 18:19 UTC
