### ISSUE TITLE
Chat window scroll bars

### ISSUE THREAD

**Issue by Dmeister406** [funkydude/BasicChatMods#86] opened 2023-05-03 10:46 UTC
In 10.1 when enabling "fade" and "button hide", the scroll bars and arrows persist when logging in for the first time or doing a /reload, until you mouse over the chat window:

![image](https://user-images.githubusercontent.com/16833/236065479-3a82e577-5eb2-40d2-b1b8-f3c75a1cce8e.png)

**Comment by Nillx** [comment] 2023-05-03 12:18
![image](https://user-images.githubusercontent.com/34476875/235913193-f9229c83-f093-49c0-84e8-3258a3074740.png)
Yeah i would love to hide that scrollbar. Its showing every time when something pop in the chat.

**Comment by funkydude** [comment] 2023-05-03 22:42
Cannot reproduce the scrollbar showing up every time something new is added to chat.

I can reproduce it showing when you log in, however, that happens even with BCM turned off.

**Comment by Dmeister406** [comment] 2023-05-03 22:44
> I can reproduce it showing when you log in, however, that happens even with BCM turned off.

OK, so that must be a Blizzard bug then.

**Comment by Rezy942** [comment] 2023-05-04 23:35
Its a known blizzard bug. To reproduce - mouseover chat to fade it IN. Instantly /reload before it fades out. When UI appears again, chat will be hidden, but scroll wheel appears.

Can also easily reproduce by hiding the UI keybind. Make chat fade in, hide UI, give it some time for fade out to happen, then re-enable UI. Scroll is there.

**Comment by Rezy942** [comment] 2023-05-20 11:28
Any update on a fix for this?
Prat has already found a way to resolve this - maybe use their code as a guide?
Please and thank you..

**Comment by funkydude** [comment] 2023-05-22 06:55
I reported it to Blizz and they have already implemented a fix in 10.1.5 PTR which you can test if you wish on the PTR realm.

**Closed** 2023-07-11 14:34 UTC
